runtime: php72

env_variables:
  APP_KEY: base64:0z6RXFFcnrGVY7U0nOeok/G3j11sKBa5bFqnZ9aN63c=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  LOG_CHANNEL: stackdriver
  DB_DATABASE: portfolio
  DB_USERNAME: portfolio_user
  DB_PASSWORD: 515253vlad
  DB_SOCKET: "/cloudsql/portfolio-275919:europe-west1:portfolio"
